#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bar settings
# yabai -m config status_bar                   off
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# yabai -m config status_bar_power_icon_strip   
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  on
yabai -m config window_shadow                   float
# yabai -m config window_shadow                   on
# yabai -m config window_opacity                  off
yabai -m config window_opacity                  on
yabai -m config window_opacity_duration         0.15
yabai -m config active_window_opacity           0.95
yabai -m config normal_window_opacity           0.85
yabai -m config window_border                   off
yabai -m config window_border_width             4
yabai -m config active_window_border_color      0xff8CABC8
yabai -m config normal_window_border_color      0xff2a2f38
yabai -m config insert_feedback_color           0xff9dd274
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config external_bar                    all:46:0

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
# yabai -m config top_padding                     10
yabai -m config bottom_padding                  8
yabai -m config left_padding                    8
yabai -m config right_padding                   8
yabai -m config window_gap                      8

# signal with sketchybar
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# specific space settings
# yabai -m config --space 2 layout             stack

# window rules
yabai -m rule --add app="^Mail$"                space=4
yabai -m rule --add app="^Safari$"              space=2
yabai -m rule --add app="^Google Chrome$"       space=2
yabai -m rule --add app="^Firefox$"             space=2
yabai -m rule --add app="^kitty$"               space=1
yabai -m rule --add app="^QQ$"                  space=4
yabai -m rule --add app="^Music$"               space=5
yabai -m rule --add app="^Spotify$"             space=5
yabai -m rule --add app="^WeChat$"              space=4
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^Dictionary$"          manage=off
# yabai -m rule --add app="^Finder$"              manage=off
